bigquery_operations:
  outputs:
    dev:
      dataset: "{{ env_var('DBT_BIGQUERY_DATASET') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: "{{ env_var('DBT_BIGQUERY_PROJECT') }}"
      threads: 1
      type: bigquery
  target: dev